// <auto-generated />
using System;
using Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(CitrixDbContext))]
    [Migration("20200208014942_ModelResha")]
    partial class ModelResha
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Battle.BattleInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumVerstuurd")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroteKoffie")
                        .HasColumnType("int");

                    b.Property<int?>("KoffieBattleId")
                        .HasColumnType("int");

                    b.Property<int>("MediumKoffie")
                        .HasColumnType("int");

                    b.Property<int>("Restaurant")
                        .HasColumnType("int");

                    b.Property<int?>("VerstuurdDoorEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KoffieBattleId");

                    b.HasIndex("VerstuurdDoorEmployeeId");

                    b.ToTable("KoffieBattleInput");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Functie")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<int>("Restaurant")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Domain.Entities.KoffieBattle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("KoffieBattle");
                });

            modelBuilder.Entity("Domain.Entities.Battle.BattleInput", b =>
                {
                    b.HasOne("Domain.Entities.KoffieBattle", null)
                        .WithMany("CurrentInput")
                        .HasForeignKey("KoffieBattleId");

                    b.HasOne("Domain.Entities.Employee", "VerstuurdDoor")
                        .WithMany()
                        .HasForeignKey("VerstuurdDoorEmployeeId");
                });
#pragma warning restore 612, 618
        }
    }
}
